######################################################################
# Automatically generated by qmake (2.01a) ven. nov. 26 01:29:21 2010
######################################################################

TEMPLATE = app
CONFIG +=  console debug
TARGET =
DEPENDPATH += . Pion
INCLUDEPATH += .

# Input
HEADERS += Echiquier.h Joueur.h mainwindow.h Piece.h
SOURCES += Echiquier.cxx Joueur.cxx main.cpp mainwindow.cpp Piece.cxx
RESOURCES += pions.qrc
